# This file is machine-generated - editing it directly is not advised

julia_version = "1.13.0-DEV"
manifest_format = "2.0"
project_hash = "493e2e0410796bce3a2a10f2d751a84c3a84ebb1"

[[deps.JuliaGrep]]
path = "."
uuid = "69714a4a-9128-4c40-a56c-db4622eb9673"
version = "0.1.0"
